// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using s1110834035_NetFinal.Data;

#nullable disable

namespace s1110834035_NetFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240612144052_UpdateAlbumsWithPhotoCount")]
    partial class UpdateAlbumsWithPhotoCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("s1110834035_NetFinal.Models.Albums", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumName = "相簿1",
                            CreationDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4829),
                            Description = "相簿描述",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AlbumName = "相簿2",
                            CreationDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4830),
                            Description = "相簿描述",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AlbumName = "相簿3",
                            CreationDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4831),
                            Description = "相簿描述",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Memo = "這是茶",
                            Name = "茶飲"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Memo = "這是茶",
                            Name = "水果茶"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Memo = "這是咖啡",
                            Name = "咖啡"
                        });
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.ImgCarousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgF")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ImgCarousels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgF = "part_1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ImgF = "part_2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ImgF = "part_3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ImgF = "part_4.jpg"
                        });
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.Photos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int?>("AlbumsId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhotoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumsId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Description = "photo1 description",
                            FilePath = "img1.jpg",
                            PhotoName = "photo1",
                            UploadDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4846),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 2,
                            Description = "photo2 description",
                            FilePath = "img2.jpg",
                            PhotoName = "photo2",
                            UploadDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4848),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            Description = "photo3 description",
                            FilePath = "img3.jpg",
                            PhotoName = "photo3",
                            UploadDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4849),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 1,
                            Description = "photo3 description",
                            FilePath = "img4.jpg",
                            PhotoName = "photo4",
                            UploadDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4850),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 1,
                            Description = "photo3 description",
                            FilePath = "img5.jpg",
                            PhotoName = "photo5",
                            UploadDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4851),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 1,
                            Description = "photo3 description",
                            FilePath = "img6.jpg",
                            PhotoName = "photo6",
                            UploadDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4852),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 1,
                            Description = "photo3 description",
                            FilePath = "img7.jpg",
                            PhotoName = "photo7",
                            UploadDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4852),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "天然的最好",
                            ImgF = "img1.jpg",
                            Name = "台灣水果茶",
                            Price = 60.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "人生的味道",
                            ImgF = "img2.jpg",
                            Name = "鐵觀音",
                            Price = 35.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "悠閒的時光",
                            ImgF = "img1.jpg",
                            Name = "美式咖啡",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "發酵與沉澱",
                            ImgF = "img1.jpg",
                            Name = "紅茶",
                            Price = 30.0
                        });
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "hapopo35@gmail.com",
                            Password = "a1",
                            RegistrationDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4803),
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@example.com",
                            Password = "a2",
                            RegistrationDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4814),
                            UserName = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@example.com",
                            Password = "a3",
                            RegistrationDate = new DateTime(2024, 6, 12, 22, 40, 51, 633, DateTimeKind.Local).AddTicks(4815),
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.Photos", b =>
                {
                    b.HasOne("s1110834035_NetFinal.Models.Albums", null)
                        .WithMany("Photos")
                        .HasForeignKey("AlbumsId");
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.Albums", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
