// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using s1110834035_NetFinal.Data;

#nullable disable

namespace s1110834035_NetFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240602160644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("s1110834035_NetFinal.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Memo = "這是茶",
                            Name = "茶飲"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Memo = "這是茶",
                            Name = "水果茶"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Memo = "這是咖啡",
                            Name = "咖啡"
                        });
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.ImgCarousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgF")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ImgCarousels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgF = "part_1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ImgF = "part_2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ImgF = "part_3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ImgF = "part_4.jpg"
                        });
                });

            modelBuilder.Entity("s1110834035_NetFinal.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "天然的最好",
                            ImgF = "img1.jpg",
                            Name = "台灣水果茶",
                            Price = 60.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "人生的味道",
                            ImgF = "img2.jpg",
                            Name = "鐵觀音",
                            Price = 35.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "悠閒的時光",
                            ImgF = "img1.jpg",
                            Name = "美式咖啡",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "發酵與沉澱",
                            ImgF = "img1.jpg",
                            Name = "紅茶",
                            Price = 30.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
